### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by lzutao**

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Wow, nice effort! I'm looking forward to it!

**Comment by mati865** [comment]
@matthiasbeyer could you release new version of ` toml-query_derive` with updated dependencies?

**Comment by matthiasbeyer** [comment]
Sure, I'll make a note. I'll make a release as soon as I can!

**Comment by mati865** [comment]
Thanks!

**Pull request merged**
