### PR TITLE
Impl traits on array and table

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This is **highly experimental and NOT TESTED AT ALL**

@Michael-F-Bryan This is for you. Feel free to test and try out. If you encounter any issues, please post them here and (if possible) provide patches with tests I can cherry-pick onto this branch!

---

I'd love to have this merged, though the code is _ugly_, _copy-pasty_ and there are no tests. I won't merge without a _huge_ set of tests. So if someone wants this to be in the codebase, provide tests (and, if possible, fixes/refactoring/etc).

### CODE REVIEW

**Comment by Michael-F-Bryan** [comment]
Looking through the PR I think I forgot how tricky this sort of thing is to do because of all the edge cases and types involved! [I implemented][1] my own poor man's version of `toml-query` on `mdbook` and that was a pain even without dealing with arrays. 

I'll see if I can work on a couple tests and refactorings to make this more polished.

[1]: https://github.com/rust-lang-nursery/mdBook/blob/e825357848d7641e10abbd9ca4bff0ff17cc73c6/src/config.rs#L130-L190

**Comment by matthiasbeyer** [comment]
Yes, the whole thing is complicated as hell. I have several pieces of code which are _almost_ the same besides mutability... which is ugly, but works :smile:
I had an implementation of this in [imag](https://imag-pim.org) before moving it to this library and enhancing it a lot and it was hell before and the code is still not nice. That's why there is no `1.0.0` release yet ... there are probably bugs in the code I did not even run into (despite I use this crate _heavily_ in imag). There are even `unimplemented!()` pathes I don't even know whether I could ever run into (and yes, I released them. I am in a `0.x.y` version, so I think this is okay).

I'd love if you can contribute in any way! :heart:

**Comment by Michael-F-Bryan** [comment]
Yeah, it's not pretty and has a fair amount of rightward drift, but from what I can see the crate is very thorough and robust. Plus it's got really good test coverage, so we can be pretty confident it does what it says!

Looking over the codebase it seems like you *should* be able to deduplicate a lot of the work being done (I'm looking at you `mut_resolver`, `non_mut_resolver`, and `mut_creating_resolver`), but on closer inspection things are *ever so slightly* off so it may not be possible to do in practice :disappointed:

**Comment by gibix** [comment]
there is someone working on this? Can I help?

**Comment by gibix** [comment]
@TheNeikos thanks for the answer. I'll play with the PR

**Comment by matthiasbeyer** [comment]
Closed as we develop on sourcehut now.

**Pull request closed without merging**
